baseURL = 'https://weekendonmars.github.io/'
locale = 'en-gb'
title = 'Weekend On Mars'
theme = 'weekendonmarstheme'

[menus]
  [[menus.main]]
    name = 'Journal'
    pageRef = '/posts'
    weight = 10
  [[menus.main]]
    name = 'What we do'
    url = '/#approach'
    weight = 20
  [[menus.main]]
    name = 'Start a conversation'
    url = 'mailto:hello@weekendonmars.com'
    weight = 30
