baseURL = 'https://weekendonmars.github.io/'
locale = 'en-gb'
title = 'Weekend On Mars'
theme = 'weekendonmarstheme'

[markup.goldmark.renderer]
  unsafe = true

[menus]
  [[menus.main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 15
  [[menus.main]]
    name = 'Start a conversation'
    url = 'mailto:hello@weekendonmars.co.uk'
    weight = 20
